name: Build a JAR in spring boot using springboot
on:
  push:
    branches:
      - restructure



jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Grant execute permission for Gradlew
        run: chmod +x ./SimplePsy-Specialist/gradlew

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./SimplePsy-Specialist
          dockerfile: ./SimplePsy-Specialist/Dockerfile
          push: true
          tags: breadlyy/psy:1.0

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 93.95.97.176 >> ~/.ssh/known_hosts

      - name: Run script on remote server
        run: ssh root@93.95.97.176 './docker_script.sh'

